radarr:
  url: "http://radarr:port"
  api_key: "your-radarr-api-key"

sonarr:
  url: "http://sonarr:port"
  token: "your-sonarr-api-key"

API_TIMEOUT: 600  # How often to check for stalled downloads, in seconds
STRIKE_COUNT: 5   # How many strikes before removing the download

log_directory: "/app/logs"