services:  
  media_cleaner:
    image: iedgir01/media_cleaner:latest
    container_name: media_cleaner
    networks:
      - media_server
    volumes:
      - '/your/path/to/media_cleaner/logs:/app/logs'
    environment:
      - RADARR_URL=http://radarr:port
      - RADARR_API_KEY=your-radarr-api-key
      - SONARR_URL=http://sonarr:port
      - SONARR_API_KEY=your-sonarr-api-key
      - API_TIMEOUT=600
      - STRIKE_COUNT=5
      - PUID=1000 #Change to your PUID
      - PGID=1000 #Change to your PGID
      - TZ=UTC #Change to your TZ
        
networks:
  media_server:
    external: true